### PR TITLE
III-3386 Integrate Sentry SDK

### PR DESCRIPTION
**Pull request by LucWollants**
### Added
 
- Added Sentry integration
 
---

https://jira.uitdatabank.be/browse/III-3386

### CODE REVIEW

**Review by bertramakers — APPROVED** [review]

**Review by jdrieghe — APPROVED** [review]
I would have made the `ErrorHandler` a class as well, but it's small enough so the closure is fine for now.

**Comment by bertramakers** [comment]
> I would have made the `ErrorHandler` a class as well, but it's small enough so the closure is fine for now.

Ah, in a call with Luc to answer some questions he had I suggested a simple closure because it seemed overkill to add yet another class to all of these repositories. But if you both prefer a class that's okay as well.

**Review by jdrieghe — APPROVED** [review]

**Comment by LucWollants** [comment]
I implemented a new approach with an `ErrorHandler` interface. This new interface has one simple method that needs to be implemented `public function handle(\Throwable $throwable): void;`

For now we only have one concrete implementation of this new interface, namely `UncaughtErrorHandler`. This handler will push the uncaught errors to Sentry.

The new `ErrorHandlerProvider` will register concrete implementations. In the future we can decide how we handle errors. Some examples: logging to a file, creating api problems, pushing to Sentry.

If this approach is fine I can also modify `udb3-silex`.

**Comment by jdrieghe** [comment]
@LucWollants I'm still a bit confused about how you would chain multiple error handlers though

**Comment by LucWollants** [comment]
> @LucWollants I'm still a bit confused about how you would chain multiple error handlers though

Chaining is not the main concern, it's more about how we handle specific errors. A user error is something we could return as an API problem or log, on the other hand a runtime error is something we want to log to Sentry.

**Comment by bertramakers** [comment]
In itself, this approach is fine by me. However I just realized this app (udb3-cdbxml-service) and udb3-silex just so happen to still be Silex apps. In other apps like udb3-search-service and jwt-provider, where we're no longer using Silex (as is also the plan for udb3-silex and udb3-cdbxml-service), we use Whoops which has its own concept of Error Handler classes.

For example https://github.com/cultuurnet/udb3-search-service/blob/master/app/Error/ApiExceptionHandler.php
And https://github.com/cultuurnet/udb3-search-service/blob/master/app/Factory/ErrorHandlerFactory.php

So while I get the idea, I'm not sure it makes sense to add this whole new abstraction of error handlers, which will require more effort to refactor later when we move away from Silex in these apps?

**Comment by bertramakers** [comment]
On a separate point, I've lately also gotten the feeling that we have added way too many abstractions for what is essentially bootstrapping in our apps in the past, which is now sometimes very confusing and/or harder to refactor when re-visiting it 4-5 years later.

Don't get me wrong, I'm all for having separate service providers, etc. And we can definitely move the closure to a class. I'm just not sure we need our own interface for this for example. The use case is that we want to track uncaught exceptions better. A single "UncaughtErrorHandler" like @jdrieghe suggested can achieve this just fine. If we want to add an additional logger later, for example, we can also add that to the same class later. It's not like we need much flexibility and separation of concerns on this layer. We want a very specific implementation for our app. We're not building a generic error handling library that requires a lot of flexibility and several layers of de-coupling.

If you disagree with this specific example that's fine, I'm not going to block this because of the interface. 😄  I'd just like us to more often take a moment in general, to check if we're not over-complicating something that's essentially some infrastructure bootstrapping.

**Comment by bertramakers** [comment]
I'll give another example from years ago that I stumbled upon a week or so ago:
We have a console command for purging (ie truncating) read model tables.

Right now, this console command requires no less than 5 interfaces/classes!

1. The console command itself: https://github.com/cultuurnet/udb3-silex/blob/master/app/Console/PurgeModelCommand.php
2. A PurgeServiceInterface: https://github.com/cultuurnet/udb3-silex/blob/master/src/Storage/PurgeServiceInterface.php
3. A DBALPurgeService: https://github.com/cultuurnet/udb3-silex/blob/master/src/Storage/DBALPurgeService.php
4. A PurgeServiceManager https://github.com/cultuurnet/udb3-silex/blob/master/src/Storage/PurgeServiceManager.php
5. A PurgeServiceProvider to bootstrap all of that: https://github.com/cultuurnet/udb3-silex/blob/master/app/PurgeServiceProvider.php

IMHO the whole thing could have been reduced to just the console command and a static class constant with a list of the tables, as is also hardcoded here but then has to go through 4 other classes first: https://github.com/cultuurnet/udb3-silex/blob/master/app/PurgeServiceProvider.php#L61-L66

**Comment by LucWollants** [comment]
For `udb3-cdbxml-service` the extra `ErrorHandler` interface is maybe overkill. I can easily change that.

Meanwhile I was working on `udb3-uitpas-service` and there I also created an `ErrorHandler` interface with one `handle` method.
The `udb3-uitpas-service` will have 2 concrete implementations: `ApiErrorHandler` and `UncaughtErrorHandler`.
Both error handlers are bootstrapped in a single `ErrorHandlerProvider` with the class names as the container identifier.
This makes it easy to call `handle` on the `UncaughtErrorHandler` inside the `try/catch` block around the `run` method. The same approach can be used to call `handle` on `ApiErrorHandler` as the callback for `$app->error`.

So I guess for `udb3-uitpas-service` it could make sense to have the interface but for `udb3-cdbxml-service` not.

**Comment by jdrieghe** [comment]
@bertramakers I fully agree with your "too many abstractions" point. My rule of thumb is never to make an interface for something that only has one implementation. This applies nicely here.

**Comment by LucWollants** [comment]
The `ErrorHandler` interface had no purpose, so I removed it.

**Comment by bertramakers** [comment]
Looks good to me, ship it! 🚀

**Review by jdrieghe — APPROVED** [review]

**Pull request merged**
